Repository ruthosuna92/frontend-ladyfitlovers, pull requests merged in 2023-10, with the labels that each got.

#51 arreglando renderizado de botones de paginado
  src/components/Pagination/Pagination.jsx
Labels: cobro por review

#53 Hebelia/auth feat(LoginModal): adjusting login styles
  src/App.jsx
  src/components/GoogleAuth/GoogleAuth.css
  src/components/LoginModal/LoginModal.jsx
  src/components/LoginModal/loginModal.css
Labels: enhancement, new feature

#61 update redirection
  src/App.jsx
  src/components/ProfileLayout/ProfileLayout.jsx
Labels: enhancement

#64 Hebelia/navbar "feat(ProfileLayout): favorites link and menu item with key"
  src/App.jsx
  src/components/NavBar/NavBar.jsx
  src/components/PaymentState/PaymentState.jsx
  src/components/Products/Products.module.css
  src/components/ProfileLayout/ProfileLayout.jsx
Labels: enhancement

#69 Hebelia/purchases "feat(paymentState)post order action update, payment state update, payment import"
  src/components/PaymentState/PaymentState.jsx
  src/components/PaymentState/payment.txt
  src/redux/Actions/Order/postOrder.js
  src/views/Payment/Payment.jsx
Labels: enhancement, new feature

#73 Altair/shopping
  src/components/CreateAcountModal/createAcountModal.css
  src/components/DataProfile/DataProfile.module.css
  src/components/NoFoundScreen/NoFoundScreen.jsx
  src/components/Pagination/Pagination.module.css
  src/components/Products/Products.module.css
  src/components/ProfileLayout/ProfileLayout.jsx
  src/components/ShoppingClient/ShoppingClient.jsx
  src/components/ShoppingClient/ShoppingClient.module.css
  src/redux/Actions/Order/getOrdersByUser.js
  src/redux/Actions/Purchase/getPurchases.js
  src/redux/Actions/actionTypes.js
  src/redux/Reducers/reducer.js
  src/views/Contac/Contac.module.css
  src/views/ProductsView/ProductsView.jsx
  src/views/ProductsView/ProductsView.module.css
Labels: enhancement, new feature
